import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/LandingPage/Footer'
import Main from '../Components/LandingPage/Main'
import Navbar from '../Components/LandingPage/Navbar'


export default function Home() {
  return (
    <div >
      <Navbar/>
      <Head>
        <title>Binder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main/>

  

      <Footer/>

      

   
    
    </div>
  )
}
